# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 870b296b2bb701b50eba17f5d0966e64a0011a2eb46611510e47cac3d01aadb226a3c5316b2e75956161ccbc7596b98188e7c02cb0b0e095529478d40a66461c

test:
  secret_key_base: c02c3a55cf65a6275d9fba5e1365405638f886502e882e144e9737c51c266fa6900bd7b6b94a2746fd7458caecadcb67f5d18781723f2d74b9218835ca58302a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
